### PR TITLE
adding support for authentication

### PR DESCRIPTION
**Pull request by luisdavim**
This is a followup PR to the one I've opened yesterday (#9), to allow users to use private registries that require authentication.

### CODE REVIEW

**Comment by luisdavim** [comment]
@ricksbrown and @alexbrazier could you guys review this PR?
Thanks.

**Comment by ricksbrown** [comment]
@luisdavim LGTM though I had one question - do you think there is now enough duplicate code in building up the request that it warrants being moved into a reusable utility module?

**Comment by alexbrazier** [comment]
Looks good, but I agree with @ricksbrown that the request or requestOptions should be moved somewhere to remove the duplicated code

**Comment by luisdavim** [comment]
Yeah, you guys are right. I'll look into that.

**Comment by luisdavim** [comment]
I've moved the request options generation to a module.

**Comment by alexbrazier** [comment]
@luisdavim Thanks! I'll try and get it merged tonight.

**Comment by alexbrazier** [comment]
Sorry for the delay on this. I wanted to change the PBRequest file to use ES6 imports to match the rest of the style.
`v0.5.0` has now been published to npm 🎉

**Pull request merged**
